(defun dark-mode ()
  (interactive)
  (disable-theme 'mark-day)
  (disable-theme 'mark-fyad)
  (load-theme 'mark-night))
(defun light-mode ()
  (interactive)
  (disable-theme 'mark-night)
  (disable-theme 'mark-fyad)
  (load-theme 'mark-day))
(defun fyad-mode ()
  (interactive)
  (disable-theme 'mark-night)
  (disable-theme 'mark-day)
  (load-theme 'mark-fyad))
