(deftheme mark-night
  "Created 2016-10-06.")

(custom-theme-set-faces
 'mark
 '(default ((t (:family "Menlo" :foundry "nil" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#C0B6A8" :background "gray13" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#D0C179"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "orange"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#1278A8"))))
 '(hl-line ((t (:foreground nil :background "gray11"))))
 '(highlight ((t (:foreground "orange"))))
 '(region ((t (:foreground "#faf4c6" :background "#2A4750"))))
 '(shadow ((t (:foreground "#777777"))))
 '(secondary-selection ((t (:background "#342858"))))
 '(trailing-whitespace ((t (:foreground "#FFFFFF" :background "#C74000"))))
 '(font-lock-builtin-face ((t (:foreground "#54686d"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5E5E5E"))))
 '(font-lock-comment-face ((t (:foreground "#5E5E5E"))))
 '(font-lock-constant-face ((t (:foreground "#A1877E"))))
 '(web-mode-symbol-face ((t (:foreground "#A1877E"))))
 '(font-lock-doc-face ((t (:foreground "#7d949b"))))
 '(font-lock-function-name-face ((t (:foreground "#7a8bbd"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#986F61"))))
 '(font-lock-negation-char-face ((t (:foreground "#f03f3f"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#CB9B48"))))
 '(font-lock-type-face ((t (:foreground "#8aa6c1"))))
 '(font-lock-variable-name-face ((t (:foreground "#8D776E"))))
 '(font-lock-warning-face ((t (:foreground "#ffffff" :background "#ff6523"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#FFFFFF" :background "#444444" :inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#00b7f0"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#4488cc" :inherit (link)))))
 '(fringe ((t (:foreground "#8aa234" :background "#272a2a"))))
 '(header-line ((t (:box nil :foreground "#EEEEEE" :background "#444444" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "LightYellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:weight bold :box nil :foreground "#c0b6a8" :background "#272a2a"))))
 '(mode-line-buffer-id ((t (:weight bold :box nil :foreground "#5d90cd"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box nil :background "#808080"))))
 '(mode-line-inactive ((t (:weight light :box nil :foreground "#a2937e" :background "#272a2a" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :foreground "#99ccee" :background "#444444"))))
 '(isearch-fail ((t (:background "#ffaaaa"))))
 '(lazy-highlight ((t (:background "#77bbdd"))))
 '(match ((t (:background "#3388cc"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'mark-night)
